version: '3.9'
services:
  backend:
    depends_on:
      - postgres
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - '4000:3000'
    links:
      - postgres

  postgres:
    container_name: 'database'
    image: postgres:12.12-alpine
    restart: on-failure
    env_file: .env

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
volumes:
  data: